! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Main Program File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : cb6_Main.f90
! Time                 : Thu Aug 31 17:04:30 2017
! Working directory    : /home/regcm/Code/kpp-2.2.3/Workspace/GAS_CB6r2_mod
! Equation file        : cb6.kpp
! Output root filename : cb6
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! MAIN - Main program - driver routine
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
module mod_cb6_main1
  use mod_cb6_Model
  use mod_cb6_Global
  use mod_cb6_Parameters

  public :: chemmain_cb6

  contains

  subroutine chemmain_cb6(jday,dtche)
    use mod_cb6_Model
    use mod_cb6_Global
    use mod_cb6_Parameters
    use mod_cb6_jval1
    implicit none
    real(kind=dp) , intent(in) :: jday , dtche

    real(kind=dp) :: t
    real(kind=dp) :: rstate(20)
    integer :: i
    integer :: icontrol(20)

!------------------Declaration part for jval----------

    integer :: c_hvin
    integer , dimension(22) :: c_nhv(22)
    real(kind=dp) , dimension(22) :: jparam
    real(kind=dp) , dimension(22,40) :: c_hvmat
    real(kind=dp) , dimension(22) :: c_hvmatb
    real(kind=dp) , dimension(80,510,56) :: c_jarray

    common /hvrvars/ c_hvmat , c_hvmatb , c_jarray
    common /HVINT/ c_hvin , c_nhv
    real(kind=dp) , dimension(56) :: jval

    integer , parameter :: jO31D  = 2
    integer , parameter :: jO33P  = 3
    integer , parameter :: jNDOX  = 4
    integer , parameter :: jNTOXb = 5
    integer , parameter :: jNTOXa = 6
    integer , parameter :: jDNPOb = 8
    integer , parameter :: jHPOX  = 11
    integer , parameter :: jHONO  = 12
    integer , parameter :: jNTRC  = 13
    integer , parameter :: jPNA   = 14
    integer , parameter :: jFORMa = 15
    integer , parameter :: jFORMb = 16
    integer , parameter :: jAALD  = 17
    integer , parameter :: jISPD  = 18
    integer , parameter :: jALDX  = 20
    integer , parameter :: jGLY   = 21
    integer , parameter :: jMEGY  = 22
    integer , parameter :: jACET  = 23
    integer , parameter :: jMEPX  = 24
    integer , parameter :: jNTR   = 25
    integer , parameter :: jPACN  = 26
    !integer , parameter :: jPANX  = 41
    !integer , parameter :: jRPOX  = 42
    !integer , parameter :: jGLYD  = 43
    !integer , parameter :: jKET   = 44
    !integer , parameter :: jHPLD  = 45
    !integer , parameter :: jCRON  = 46
    !integer , parameter :: jXOPN  = 47
    !integer , parameter :: jROPN  = 48

    !~~~> Initialization 

    var => c_cb6(1:nvar_cb6)
    fix => c_cb6(nvar_cb6+1:)

    stepmin = 0.0d0
    stepmax = 0.0d0

    do i = 1 , nvar_cb6
      rtol(i) = 0.1D0
      atol(i) = 0.1D0
    end do
!   fix(1) = (3.0E+5)*C_Mb
    fix(1) = wtrin
    fix(2) = (0.00000055D0)*C_Mb !DIHY   -  0.000055 %
    fix(3) = (0.20946000D0)*C_Mb !O2     - 20.946000 %
!   fix(4) = (0.00000180D0)*C_Mb !METH   -  0.000180 %
    fix(4) = (0.78084000D0)*C_Mb !M (N2) - 78.084000 %
!   fix(5) = (0.22D0)*C_Mb !DUMMY2 as O2

    !call loadperoxyparameters

    ! constant rate coefficients
    rconst(11) = ((2.14D-10))
    rconst(31) = ((1.70D-11))
    rconst(32) = ((2.00D-11))
    rconst(33) = ((4.00D-12))
    rconst(34) = ((1.00D-17))
    rconst(39) = ((1.00D-22))
    rconst(41) = ((5.00D-40))
    rconst(42) = ((1.00D-20))
    rconst(91) = ((2.00D-12))
    rconst(93) = ((4.50D-13))
    rconst(100) = ((5.50D-16))
    rconst(103) = ((5.60D-12))
    rconst(111) = ((6.30D-15))
    rconst(113) = ((8.00D-12))
    rconst(132) = ((8.10D-13))
    rconst(145) = ((2.30D-11))
    rconst(148) = ((3.70D-13))
    rconst(150) = ((3.00D-11))
    rconst(170) = ((3.10D-11))
    rconst(171) = ((3.60D-11))
    rconst(185) = ((1.85D-11))
    rconst(191) = ((1.40D-11))
    rconst(192) = ((2.10D-12))
    rconst(193) = ((5.50D-12))
    rconst(194) = ((1.53D-12))
    rconst(195) = ((3.80D-12))
    rconst(198) = ((9.00D-11))
    rconst(200) = ((3.00D-12))
    rconst(202) = ((4.40D-11))
    rconst(204) = ((3.80D-12))
    rconst(205) = ((5.00D-11))
    rconst(206) = ((1.70D-10))
    rconst(207) = ((1.00D-11))
    rconst(213) = ((3.60D-11))
    rconst(214) = ((3.00D-12))
    rconst(215) = ((2.30D-05))

    tstart = 0.0D0*3600.0D0
    dt = dtche

    do i = 1 , nvar_cb6
      var(i)  = xrinb(i)
    end do
    t = tstart
    tend = tstart+dtche

    timeb = t
    jparam(1) = zenithb
    jparam(2) = altmidb
    jparam(3) = 330._dp
    jparam(4) = 0.1_dp
    jparam(5) = 0.1_dp
    jparam(6) = 0.38_dp
    jparam(7) = 0.85_dp
    jparam(8) = 0.1_dp
    jparam(9) = depthab
    jparam(10)= depthbb
    jparam(11)= altaboveb
    jparam(12)= altbelowb
    jparam(13)= tempb
    jparam(20)= jday

    call jvalpro(c_nhv,c_hvmat,c_jarray,jparam,jval) 
    jval_O31D    =  jval(jO31D)  ! ozone
    jval_O33P    =  jval(jO33P)  ! ozone
    jval_NDOX    =  jval(jNDOX)  ! nitrogen dioxide
    jval_NTOXa   =  jval(jNTOXa) ! nitrate radical
    jval_NTOXb   =  jval(jNTOXb) ! nitrate radical
    jval_DNPOb   =  jval(jDNPOb) ! dinitrogen pentoxide
    jval_HPOX    =  jval(jHPOX)  ! hydrogen peroxide
    jval_HONO    =  jval(jHONO)  ! nitrous acid
    jval_NTRC    =  jval(jNTRC)  ! nitric acid
    jval_PNA     =  jval(jPNA)   ! peroxynitric acid
    jval_FORMa   =  jval(jFORMa) ! formalydehyde
    jval_FORMb   =  jval(jFORMb) ! formalydehyde
    jval_AALD    =  jval(jAALD)  ! acetaldehyde
    jval_ISPD    =  jval(jISPD)  ! methacrolein
    jval_ALDX    =  jval(jALDX)  ! propionaldehyde
    jval_GLY     =  jval(jGLY)   ! glyoxal
    jval_MEGY    =  jval(jMEGY)  ! methylglyoxal
    jval_ACET    =  jval(jACET)  ! acetone
    jval_MEPX    =  jval(jMEPX)  ! methylhydroperoxide
    jval_NTR     =  jval(jNTR)   ! butyl nitrate
    jval_PACN    =  jval(jPACN)  ! peroxyacetyl nitrate
    ! list jvals using substitute data 
    jval_PANX    = jval_PACN ! C3+ peroxyacyl nitrate
    jval_RPOX    = jval_MEPX ! butyl hydroperoxide
    jval_GLYD    = jval_ISPD ! glycolaldehyde
    jval_KET     = jval_ACET ! methyl ethyl ketone
    jval_HPLD    = jval_MEPX ! (Z)-4-Hydroperoxy-3-methyl-2-butenal
    jval_CRON    = jval_NTR  ! nitro-cresols
    jval_XOPN    = jval_GLY  ! 2-pentenedial
    jval_ROPN    = jval_GLY  ! butenedial
    c_jvalb(1,:) = jval(:)

    icontrol = (/ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 /)
    kron: &
    do while (t < tend)
      call update_rconst()
      call integrate( tin = t, tout = t+dt, rstatus_u = rstate, &
               icntrl_u = icontrol)
      t = rstate(1)
    end do kron

    do i = 1 , nvar_cb6
      xroutb(i) = var(i)
    end do
    wtrout = fix(1)

    end subroutine chemmain_cb6

end module  mod_cb6_main1

! End of MAIN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


